//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSpecificMemberDetailsOffNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.memberBasicInfo[] getSpecificMemberDetailsOffNo(string OffNo, string ServiceType, string OS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSpecificMemberDetailsOffNo", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.memberBasicInfo[]> getSpecificMemberDetailsOffNoAsync(string OffNo, string ServiceType, string OS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSpecificMemberDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.memberBasicInfo[] getSpecificMemberDetails(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSpecificMemberDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.memberBasicInfo[]> getSpecificMemberDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBirthday", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.birthdayDetails[] getBirthday(string selectedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBirthday", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.birthdayDetails[]> getBirthdayAsync(string selectedDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSpecificMemberLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiceReference1.memberLoginInfo[] getSpecificMemberLogin(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSpecificMemberLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.memberLoginInfo[]> getSpecificMemberLoginAsync(string userName, string password);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class memberBasicInfo
    {
        
        private string nICField;
        
        private string navyIdField;
        
        private string officialNoField;
        
        private string serviceTypeField;
        
        private string officerSailorField;
        
        private string rankField;
        
        private string initialsField;
        
        private string surnameField;
        
        private string fullNameField;
        
        private string permenentAddressField;
        
        private string branchField;
        
        private string civilStatusField;
        
        private string dateOfMarriageField;
        
        private string establishmentField;
        
        private string dOBField;
        
        private string emailField;
        
        private string imageField;
        
        private string isActiveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NIC
        {
            get
            {
                return this.nICField;
            }
            set
            {
                this.nICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NavyId
        {
            get
            {
                return this.navyIdField;
            }
            set
            {
                this.navyIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OfficialNo
        {
            get
            {
                return this.officialNoField;
            }
            set
            {
                this.officialNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ServiceType
        {
            get
            {
                return this.serviceTypeField;
            }
            set
            {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OfficerSailor
        {
            get
            {
                return this.officerSailorField;
            }
            set
            {
                this.officerSailorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Rank
        {
            get
            {
                return this.rankField;
            }
            set
            {
                this.rankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Initials
        {
            get
            {
                return this.initialsField;
            }
            set
            {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PermenentAddress
        {
            get
            {
                return this.permenentAddressField;
            }
            set
            {
                this.permenentAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Branch
        {
            get
            {
                return this.branchField;
            }
            set
            {
                this.branchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CivilStatus
        {
            get
            {
                return this.civilStatusField;
            }
            set
            {
                this.civilStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DateOfMarriage
        {
            get
            {
                return this.dateOfMarriageField;
            }
            set
            {
                this.dateOfMarriageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Establishment
        {
            get
            {
                return this.establishmentField;
            }
            set
            {
                this.establishmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string DOB
        {
            get
            {
                return this.dOBField;
            }
            set
            {
                this.dOBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string IsActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class memberLoginInfo
    {
        
        private string isValidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string isValid
        {
            get
            {
                return this.isValidField;
            }
            set
            {
                this.isValidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class birthdayDetails
    {
        
        private string imageField;
        
        private string branchIDField;
        
        private string officialNoField;
        
        private string rankRateField;
        
        private string initialsField;
        
        private string surenameField;
        
        private string baseNameField;
        
        private string dateOfBirthField;
        
        private string presentTPField;
        
        private string mobileTPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string branchID
        {
            get
            {
                return this.branchIDField;
            }
            set
            {
                this.branchIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string officialNo
        {
            get
            {
                return this.officialNoField;
            }
            set
            {
                this.officialNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string rankRate
        {
            get
            {
                return this.rankRateField;
            }
            set
            {
                this.rankRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string initials
        {
            get
            {
                return this.initialsField;
            }
            set
            {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string surename
        {
            get
            {
                return this.surenameField;
            }
            set
            {
                this.surenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string baseName
        {
            get
            {
                return this.baseNameField;
            }
            set
            {
                this.baseNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string dateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string presentTP
        {
            get
            {
                return this.presentTPField;
            }
            set
            {
                this.presentTPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string mobileTP
        {
            get
            {
                return this.mobileTPField;
            }
            set
            {
                this.mobileTPField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface Service1SoapChannel : ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<ServiceReference1.Service1Soap>, ServiceReference1.Service1Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), Service1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReference1.memberBasicInfo[] getSpecificMemberDetailsOffNo(string OffNo, string ServiceType, string OS)
        {
            return base.Channel.getSpecificMemberDetailsOffNo(OffNo, ServiceType, OS);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.memberBasicInfo[]> getSpecificMemberDetailsOffNoAsync(string OffNo, string ServiceType, string OS)
        {
            return base.Channel.getSpecificMemberDetailsOffNoAsync(OffNo, ServiceType, OS);
        }
        
        public ServiceReference1.memberBasicInfo[] getSpecificMemberDetails(string NIC)
        {
            return base.Channel.getSpecificMemberDetails(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.memberBasicInfo[]> getSpecificMemberDetailsAsync(string NIC)
        {
            return base.Channel.getSpecificMemberDetailsAsync(NIC);
        }
        
        public ServiceReference1.birthdayDetails[] getBirthday(string selectedDate)
        {
            return base.Channel.getBirthday(selectedDate);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.birthdayDetails[]> getBirthdayAsync(string selectedDate)
        {
            return base.Channel.getBirthdayAsync(selectedDate);
        }
        
        public ServiceReference1.memberLoginInfo[] getSpecificMemberLogin(string userName, string password)
        {
            return base.Channel.getSpecificMemberLogin(userName, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.memberLoginInfo[]> getSpecificMemberLoginAsync(string userName, string password)
        {
            return base.Channel.getSpecificMemberLoginAsync(userName, password);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.1.216:98/Service1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.1.216:98/Service1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Service1Soap,
            
            Service1Soap12,
        }
    }
}
