//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.Service1Soap")]
    public interface Service1Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSpecificMemberBasicInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.memberBasicInfoNBF[]> getSpecificMemberBasicInfoAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getServiceRecords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.ServiceRecordHRMS[]> getServiceRecordsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMedalAndDecoration", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.MedalAndDecorationHRMS[]> getMedalAndDecorationAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInsignia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.InsigniaHRMS[]> getInsigniaAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDependentBasicInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.DependentBasicInfoHRMS[]> getDependentBasicInfoAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPetDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.PetDetailsHRMS[]> getPetDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSwimmingDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.SwimmingDetailsHRMS[]> getSwimmingDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWeaponDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.WeaponDetailsHRMS[]> getWeaponDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getALDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.ALDetailsHRMS[]> getALDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOLDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.OLDetailsHRMS[]> getOLDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getKitZise", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.KitZiseHRMS[]> getKitZiseAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSportDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.SportDetailsHRMS[]> getSportDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNavalDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.NavalDetailsHRMS[]> getNavalDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGCBDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.GCBDetailsHRMS[]> getGCBDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSchoolDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.SchoolDetailsHRMS[]> getSchoolDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCourseDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.CourseDetailsHRMS[]> getCourseDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getExamDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.ExamDetailsHRMS[]> getExamDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBirthDayMedicalDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.BirthDayMedicalDetailsHRMS[]> getBirthDayMedicalDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTatooDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.TatooDetailsHRMS[]> getTatooDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPunishmentDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.PunishmentDetailsHRMS[]> getPunishmentDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getArrestedSurrenderDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.ArrestedSurrenderDetailsHRMS[]> getArrestedSurrenderDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getToursVisitsSeminar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.ToursVisitsSeminar[]> getToursVisitsSeminarAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getSpecialQulificationDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.SpecialQulificationDetailsHRMS[]> getSpecialQulificationDetailsAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPromotionAdvancement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.PromotionAdvancementHRMS[]> getPromotionAdvancementAsync(string NIC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getColoursDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference2.ColoursDetailsHRMS[]> getColoursDetailsAsync(string NIC);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class memberBasicInfoNBF
    {
        
        private string nICField;
        
        private string officialNoField;
        
        private string serviceTypeField;
        
        private string fullNameField;
        
        private string rankField;
        
        private string permenentAddressField;
        
        private string temporaryAddressField;
        
        private string branchField;
        
        private string civilStatusField;
        
        private string dateOfMarriageField;
        
        private string establishmentField;
        
        private string officerSailorField;
        
        private string isActiveField;
        
        private string dOBField;
        
        private string genderField;
        
        private string initialsField;
        
        private string surnameField;
        
        private string navyJoinedDateField;
        
        private string reEngagementDateField;
        
        private string inactiveReasonField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NIC
        {
            get
            {
                return this.nICField;
            }
            set
            {
                this.nICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OfficialNo
        {
            get
            {
                return this.officialNoField;
            }
            set
            {
                this.officialNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ServiceType
        {
            get
            {
                return this.serviceTypeField;
            }
            set
            {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Rank
        {
            get
            {
                return this.rankField;
            }
            set
            {
                this.rankField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PermenentAddress
        {
            get
            {
                return this.permenentAddressField;
            }
            set
            {
                this.permenentAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TemporaryAddress
        {
            get
            {
                return this.temporaryAddressField;
            }
            set
            {
                this.temporaryAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Branch
        {
            get
            {
                return this.branchField;
            }
            set
            {
                this.branchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CivilStatus
        {
            get
            {
                return this.civilStatusField;
            }
            set
            {
                this.civilStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DateOfMarriage
        {
            get
            {
                return this.dateOfMarriageField;
            }
            set
            {
                this.dateOfMarriageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Establishment
        {
            get
            {
                return this.establishmentField;
            }
            set
            {
                this.establishmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string OfficerSailor
        {
            get
            {
                return this.officerSailorField;
            }
            set
            {
                this.officerSailorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string IsActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string DOB
        {
            get
            {
                return this.dOBField;
            }
            set
            {
                this.dOBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Gender
        {
            get
            {
                return this.genderField;
            }
            set
            {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Initials
        {
            get
            {
                return this.initialsField;
            }
            set
            {
                this.initialsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Surname
        {
            get
            {
                return this.surnameField;
            }
            set
            {
                this.surnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string NavyJoinedDate
        {
            get
            {
                return this.navyJoinedDateField;
            }
            set
            {
                this.navyJoinedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ReEngagementDate
        {
            get
            {
                return this.reEngagementDateField;
            }
            set
            {
                this.reEngagementDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string InactiveReason
        {
            get
            {
                return this.inactiveReasonField;
            }
            set
            {
                this.inactiveReasonField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ColoursDetailsHRMS
    {
        
        private string sportField;
        
        private string colourField;
        
        private string awardedYearField;
        
        private string referenceField;
        
        private string referenceDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Sport
        {
            get
            {
                return this.sportField;
            }
            set
            {
                this.sportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Colour
        {
            get
            {
                return this.colourField;
            }
            set
            {
                this.colourField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AwardedYear
        {
            get
            {
                return this.awardedYearField;
            }
            set
            {
                this.awardedYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReferenceDate
        {
            get
            {
                return this.referenceDateField;
            }
            set
            {
                this.referenceDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PromotionAdvancementHRMS
    {
        
        private string rankRateField;
        
        private string promotionAdvancementDateField;
        
        private string signalReferenceField;
        
        private string signalReferenceDateField;
        
        private string signalTypeField;
        
        private string remarksField;
        
        private string nextPromotionAdvancementDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RankRate
        {
            get
            {
                return this.rankRateField;
            }
            set
            {
                this.rankRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PromotionAdvancementDate
        {
            get
            {
                return this.promotionAdvancementDateField;
            }
            set
            {
                this.promotionAdvancementDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SignalReference
        {
            get
            {
                return this.signalReferenceField;
            }
            set
            {
                this.signalReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SignalReferenceDate
        {
            get
            {
                return this.signalReferenceDateField;
            }
            set
            {
                this.signalReferenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SignalType
        {
            get
            {
                return this.signalTypeField;
            }
            set
            {
                this.signalTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NextPromotionAdvancementDate
        {
            get
            {
                return this.nextPromotionAdvancementDateField;
            }
            set
            {
                this.nextPromotionAdvancementDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SpecialQulificationDetailsHRMS
    {
        
        private string professionalQualificationField;
        
        private string instituteNameField;
        
        private string gradeField;
        
        private string yearField;
        
        private string countryNameField;
        
        private string nVQLevelField;
        
        private string pqTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProfessionalQualification
        {
            get
            {
                return this.professionalQualificationField;
            }
            set
            {
                this.professionalQualificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InstituteName
        {
            get
            {
                return this.instituteNameField;
            }
            set
            {
                this.instituteNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CountryName
        {
            get
            {
                return this.countryNameField;
            }
            set
            {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NVQLevel
        {
            get
            {
                return this.nVQLevelField;
            }
            set
            {
                this.nVQLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string pqType
        {
            get
            {
                return this.pqTypeField;
            }
            set
            {
                this.pqTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ToursVisitsSeminar
    {
        
        private string discriptionField;
        
        private string referenceField;
        
        private string referenceDateField;
        
        private string fromField;
        
        private string toField;
        
        private string venueField;
        
        private string countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Discription
        {
            get
            {
                return this.discriptionField;
            }
            set
            {
                this.discriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReferenceDate
        {
            get
            {
                return this.referenceDateField;
            }
            set
            {
                this.referenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string From
        {
            get
            {
                return this.fromField;
            }
            set
            {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string To
        {
            get
            {
                return this.toField;
            }
            set
            {
                this.toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Venue
        {
            get
            {
                return this.venueField;
            }
            set
            {
                this.venueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ArrestedSurrenderDetailsHRMS
    {
        
        private string referenceField;
        
        private string referenceDateField;
        
        private string baseField;
        
        private string statusField;
        
        private string arrestedSurrendedDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ReferenceDate
        {
            get
            {
                return this.referenceDateField;
            }
            set
            {
                this.referenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ArrestedSurrendedDate
        {
            get
            {
                return this.arrestedSurrendedDateField;
            }
            set
            {
                this.arrestedSurrendedDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PunishmentDetailsHRMS
    {
        
        private string dateOfVGBrakeField;
        
        private string dateOfVGCommenceField;
        
        private string punishmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DateOfVGBrake
        {
            get
            {
                return this.dateOfVGBrakeField;
            }
            set
            {
                this.dateOfVGBrakeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DateOfVGCommence
        {
            get
            {
                return this.dateOfVGCommenceField;
            }
            set
            {
                this.dateOfVGCommenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Punishment
        {
            get
            {
                return this.punishmentField;
            }
            set
            {
                this.punishmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TatooDetailsHRMS
    {
        
        private string tatooDetailsField;
        
        private string tatooImageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TatooDetails
        {
            get
            {
                return this.tatooDetailsField;
            }
            set
            {
                this.tatooDetailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TatooImage
        {
            get
            {
                return this.tatooImageField;
            }
            set
            {
                this.tatooImageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BirthDayMedicalDetailsHRMS
    {
        
        private string dateOfBirthField;
        
        private string ageField;
        
        private string ageGroupField;
        
        private string medicalDueDateField;
        
        private string referenceField;
        
        private string medicalDateField;
        
        private string medicalStatusField;
        
        private string remarksField;
        
        private string nextMedicalDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Age
        {
            get
            {
                return this.ageField;
            }
            set
            {
                this.ageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AgeGroup
        {
            get
            {
                return this.ageGroupField;
            }
            set
            {
                this.ageGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MedicalDueDate
        {
            get
            {
                return this.medicalDueDateField;
            }
            set
            {
                this.medicalDueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MedicalDate
        {
            get
            {
                return this.medicalDateField;
            }
            set
            {
                this.medicalDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string MedicalStatus
        {
            get
            {
                return this.medicalStatusField;
            }
            set
            {
                this.medicalStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string NextMedicalDate
        {
            get
            {
                return this.nextMedicalDateField;
            }
            set
            {
                this.nextMedicalDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ExamDetailsHRMS
    {
        
        private string examNameField;
        
        private string statusField;
        
        private string examDateField;
        
        private string referenceField;
        
        private string referenceDateField;
        
        private string averageMarksField;
        
        private string achievementField;
        
        private string remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ExamName
        {
            get
            {
                return this.examNameField;
            }
            set
            {
                this.examNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ExamDate
        {
            get
            {
                return this.examDateField;
            }
            set
            {
                this.examDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReferenceDate
        {
            get
            {
                return this.referenceDateField;
            }
            set
            {
                this.referenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AverageMarks
        {
            get
            {
                return this.averageMarksField;
            }
            set
            {
                this.averageMarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Achievement
        {
            get
            {
                return this.achievementField;
            }
            set
            {
                this.achievementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CourseDetailsHRMS
    {
        
        private string courseNameField;
        
        private string statusField;
        
        private string fromDateField;
        
        private string toDateField;
        
        private string referenceField;
        
        private string referenceDateField;
        
        private string instituteNameField;
        
        private string countryNameField;
        
        private string averageMarksField;
        
        private string durationField;
        
        private string achievementField;
        
        private string courseSubCatogaryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CourseName
        {
            get
            {
                return this.courseNameField;
            }
            set
            {
                this.courseNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ToDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ReferenceDate
        {
            get
            {
                return this.referenceDateField;
            }
            set
            {
                this.referenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string InstituteName
        {
            get
            {
                return this.instituteNameField;
            }
            set
            {
                this.instituteNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CountryName
        {
            get
            {
                return this.countryNameField;
            }
            set
            {
                this.countryNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string AverageMarks
        {
            get
            {
                return this.averageMarksField;
            }
            set
            {
                this.averageMarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Achievement
        {
            get
            {
                return this.achievementField;
            }
            set
            {
                this.achievementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CourseSubCatogary
        {
            get
            {
                return this.courseSubCatogaryField;
            }
            set
            {
                this.courseSubCatogaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SchoolDetailsHRMS
    {
        
        private string schoolNameField;
        
        private string schoolDivisionField;
        
        private string schoolZoneField;
        
        private string attendedFromField;
        
        private string attendedToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SchoolName
        {
            get
            {
                return this.schoolNameField;
            }
            set
            {
                this.schoolNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SchoolDivision
        {
            get
            {
                return this.schoolDivisionField;
            }
            set
            {
                this.schoolDivisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SchoolZone
        {
            get
            {
                return this.schoolZoneField;
            }
            set
            {
                this.schoolZoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AttendedFrom
        {
            get
            {
                return this.attendedFromField;
            }
            set
            {
                this.attendedFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AttendedTo
        {
            get
            {
                return this.attendedToField;
            }
            set
            {
                this.attendedToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GCBDetailsHRMS
    {
        
        private string goodConductBadgeField;
        
        private string awardDateField;
        
        private string fileReferenceField;
        
        private string referenceDateField;
        
        private string removeDateField;
        
        private string restoreDateField;
        
        private string aTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GoodConductBadge
        {
            get
            {
                return this.goodConductBadgeField;
            }
            set
            {
                this.goodConductBadgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AwardDate
        {
            get
            {
                return this.awardDateField;
            }
            set
            {
                this.awardDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FileReference
        {
            get
            {
                return this.fileReferenceField;
            }
            set
            {
                this.fileReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ReferenceDate
        {
            get
            {
                return this.referenceDateField;
            }
            set
            {
                this.referenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RemoveDate
        {
            get
            {
                return this.removeDateField;
            }
            set
            {
                this.removeDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RestoreDate
        {
            get
            {
                return this.restoreDateField;
            }
            set
            {
                this.restoreDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string AType
        {
            get
            {
                return this.aTypeField;
            }
            set
            {
                this.aTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class NavalDetailsHRMS
    {
        
        private string officerSailorField;
        
        private string serviceTypeField;
        
        private string branchField;
        
        private string categoryOfBranchField;
        
        private string specializationField;
        
        private string navyIdNumberField;
        
        private string navyIdExpireDateField;
        
        private string entryField;
        
        private string intakeField;
        
        private string dateOfEnlistmentField;
        
        private string servicePeriodField;
        
        private string bondPeriodField;
        
        private string permanentAreaField;
        
        private string temporarilyAreaField;
        
        private string temporarilySubUnitField;
        
        private string specializationHistoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OfficerSailor
        {
            get
            {
                return this.officerSailorField;
            }
            set
            {
                this.officerSailorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ServiceType
        {
            get
            {
                return this.serviceTypeField;
            }
            set
            {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Branch
        {
            get
            {
                return this.branchField;
            }
            set
            {
                this.branchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CategoryOfBranch
        {
            get
            {
                return this.categoryOfBranchField;
            }
            set
            {
                this.categoryOfBranchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Specialization
        {
            get
            {
                return this.specializationField;
            }
            set
            {
                this.specializationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NavyIdNumber
        {
            get
            {
                return this.navyIdNumberField;
            }
            set
            {
                this.navyIdNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NavyIdExpireDate
        {
            get
            {
                return this.navyIdExpireDateField;
            }
            set
            {
                this.navyIdExpireDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Entry
        {
            get
            {
                return this.entryField;
            }
            set
            {
                this.entryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Intake
        {
            get
            {
                return this.intakeField;
            }
            set
            {
                this.intakeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string DateOfEnlistment
        {
            get
            {
                return this.dateOfEnlistmentField;
            }
            set
            {
                this.dateOfEnlistmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ServicePeriod
        {
            get
            {
                return this.servicePeriodField;
            }
            set
            {
                this.servicePeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string BondPeriod
        {
            get
            {
                return this.bondPeriodField;
            }
            set
            {
                this.bondPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string PermanentArea
        {
            get
            {
                return this.permanentAreaField;
            }
            set
            {
                this.permanentAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string TemporarilyArea
        {
            get
            {
                return this.temporarilyAreaField;
            }
            set
            {
                this.temporarilyAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string TemporarilySubUnit
        {
            get
            {
                return this.temporarilySubUnitField;
            }
            set
            {
                this.temporarilySubUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string SpecializationHistory
        {
            get
            {
                return this.specializationHistoryField;
            }
            set
            {
                this.specializationHistoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SportDetailsHRMS
    {
        
        private string signalDateField;
        
        private string referenceField;
        
        private string sportField;
        
        private string eventField;
        
        private string representUnitField;
        
        private string positionField;
        
        private string result1Field;
        
        private string result2Field;
        
        private string result3Field;
        
        private string result4Field;
        
        private string result5Field;
        
        private string teamResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SignalDate
        {
            get
            {
                return this.signalDateField;
            }
            set
            {
                this.signalDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Sport
        {
            get
            {
                return this.sportField;
            }
            set
            {
                this.sportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Event
        {
            get
            {
                return this.eventField;
            }
            set
            {
                this.eventField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RepresentUnit
        {
            get
            {
                return this.representUnitField;
            }
            set
            {
                this.representUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Result1
        {
            get
            {
                return this.result1Field;
            }
            set
            {
                this.result1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Result2
        {
            get
            {
                return this.result2Field;
            }
            set
            {
                this.result2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Result3
        {
            get
            {
                return this.result3Field;
            }
            set
            {
                this.result3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Result4
        {
            get
            {
                return this.result4Field;
            }
            set
            {
                this.result4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Result5
        {
            get
            {
                return this.result5Field;
            }
            set
            {
                this.result5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string TeamResult
        {
            get
            {
                return this.teamResultField;
            }
            set
            {
                this.teamResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KitZiseHRMS
    {
        
        private string waistSizeField;
        
        private string collarSizeField;
        
        private string tShirtSizeField;
        
        private string capSizeField;
        
        private string shoesSizeField;
        
        private string deckShoeSizeField;
        
        private string bootSizeField;
        
        private string overallSizeField;
        
        private string jeanVestSizeField;
        
        private string rainCapSizeField;
        
        private string bannionSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string WaistSize
        {
            get
            {
                return this.waistSizeField;
            }
            set
            {
                this.waistSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CollarSize
        {
            get
            {
                return this.collarSizeField;
            }
            set
            {
                this.collarSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TShirtSize
        {
            get
            {
                return this.tShirtSizeField;
            }
            set
            {
                this.tShirtSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CapSize
        {
            get
            {
                return this.capSizeField;
            }
            set
            {
                this.capSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ShoesSize
        {
            get
            {
                return this.shoesSizeField;
            }
            set
            {
                this.shoesSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DeckShoeSize
        {
            get
            {
                return this.deckShoeSizeField;
            }
            set
            {
                this.deckShoeSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string BootSize
        {
            get
            {
                return this.bootSizeField;
            }
            set
            {
                this.bootSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OverallSize
        {
            get
            {
                return this.overallSizeField;
            }
            set
            {
                this.overallSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string JeanVestSize
        {
            get
            {
                return this.jeanVestSizeField;
            }
            set
            {
                this.jeanVestSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RainCapSize
        {
            get
            {
                return this.rainCapSizeField;
            }
            set
            {
                this.rainCapSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string BannionSize
        {
            get
            {
                return this.bannionSizeField;
            }
            set
            {
                this.bannionSizeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OLDetailsHRMS
    {
        
        private string subjectNameField;
        
        private string gradeField;
        
        private string indexNumberField;
        
        private string yearField;
        
        private string examTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubjectName
        {
            get
            {
                return this.subjectNameField;
            }
            set
            {
                this.subjectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IndexNumber
        {
            get
            {
                return this.indexNumberField;
            }
            set
            {
                this.indexNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ExamType
        {
            get
            {
                return this.examTypeField;
            }
            set
            {
                this.examTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ALDetailsHRMS
    {
        
        private string subjectNameField;
        
        private string gradeField;
        
        private string indexNumberField;
        
        private string yearField;
        
        private string examTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubjectName
        {
            get
            {
                return this.subjectNameField;
            }
            set
            {
                this.subjectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Grade
        {
            get
            {
                return this.gradeField;
            }
            set
            {
                this.gradeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IndexNumber
        {
            get
            {
                return this.indexNumberField;
            }
            set
            {
                this.indexNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Year
        {
            get
            {
                return this.yearField;
            }
            set
            {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ExamType
        {
            get
            {
                return this.examTypeField;
            }
            set
            {
                this.examTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WeaponDetailsHRMS
    {
        
        private string examTypeField;
        
        private string examStatusField;
        
        private string baseNameField;
        
        private string examDateField;
        
        private string referenceField;
        
        private string referenceDateField;
        
        private string remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ExamType
        {
            get
            {
                return this.examTypeField;
            }
            set
            {
                this.examTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExamStatus
        {
            get
            {
                return this.examStatusField;
            }
            set
            {
                this.examStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BaseName
        {
            get
            {
                return this.baseNameField;
            }
            set
            {
                this.baseNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ExamDate
        {
            get
            {
                return this.examDateField;
            }
            set
            {
                this.examDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ReferenceDate
        {
            get
            {
                return this.referenceDateField;
            }
            set
            {
                this.referenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SwimmingDetailsHRMS
    {
        
        private string examTypeField;
        
        private string examStatusField;
        
        private string baseNameField;
        
        private string examDateField;
        
        private string referenceField;
        
        private string referenceDateField;
        
        private string remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ExamType
        {
            get
            {
                return this.examTypeField;
            }
            set
            {
                this.examTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExamStatus
        {
            get
            {
                return this.examStatusField;
            }
            set
            {
                this.examStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BaseName
        {
            get
            {
                return this.baseNameField;
            }
            set
            {
                this.baseNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ExamDate
        {
            get
            {
                return this.examDateField;
            }
            set
            {
                this.examDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ReferenceDate
        {
            get
            {
                return this.referenceDateField;
            }
            set
            {
                this.referenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PetDetailsHRMS
    {
        
        private string examStatusField;
        
        private string examYearField;
        
        private string effectiveDateField;
        
        private string referenceField;
        
        private string referenceDateField;
        
        private string remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ExamStatus
        {
            get
            {
                return this.examStatusField;
            }
            set
            {
                this.examStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ExamYear
        {
            get
            {
                return this.examYearField;
            }
            set
            {
                this.examYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EffectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ReferenceDate
        {
            get
            {
                return this.referenceDateField;
            }
            set
            {
                this.referenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DependentBasicInfoHRMS
    {
        
        private string dependantNameField;
        
        private string dependantDescriptionField;
        
        private string dependantNICField;
        
        private string dateOfBirthDependantField;
        
        private string dependantAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DependantName
        {
            get
            {
                return this.dependantNameField;
            }
            set
            {
                this.dependantNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DependantDescription
        {
            get
            {
                return this.dependantDescriptionField;
            }
            set
            {
                this.dependantDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DependantNIC
        {
            get
            {
                return this.dependantNICField;
            }
            set
            {
                this.dependantNICField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DateOfBirthDependant
        {
            get
            {
                return this.dateOfBirthDependantField;
            }
            set
            {
                this.dateOfBirthDependantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DependantAddress
        {
            get
            {
                return this.dependantAddressField;
            }
            set
            {
                this.dependantAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InsigniaHRMS
    {
        
        private string insigniaNameField;
        
        private string referenceField;
        
        private string referenceDateField;
        
        private string awardedYearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InsigniaName
        {
            get
            {
                return this.insigniaNameField;
            }
            set
            {
                this.insigniaNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReferenceDate
        {
            get
            {
                return this.referenceDateField;
            }
            set
            {
                this.referenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AwardedYear
        {
            get
            {
                return this.awardedYearField;
            }
            set
            {
                this.awardedYearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MedalAndDecorationHRMS
    {
        
        private string medalNameField;
        
        private string medalTypeField;
        
        private string fileReferenceField;
        
        private string referenceDateField;
        
        private string awardedYearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MedalName
        {
            get
            {
                return this.medalNameField;
            }
            set
            {
                this.medalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MedalType
        {
            get
            {
                return this.medalTypeField;
            }
            set
            {
                this.medalTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FileReference
        {
            get
            {
                return this.fileReferenceField;
            }
            set
            {
                this.fileReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ReferenceDate
        {
            get
            {
                return this.referenceDateField;
            }
            set
            {
                this.referenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AwardedYear
        {
            get
            {
                return this.awardedYearField;
            }
            set
            {
                this.awardedYearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ServiceRecordHRMS
    {
        
        private string rankRateField;
        
        private string baseField;
        
        private string subunitField;
        
        private string fromDateField;
        
        private string toDateField;
        
        private string referanceField;
        
        private string appointmentField;
        
        private string remarksField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RankRate
        {
            get
            {
                return this.rankRateField;
            }
            set
            {
                this.rankRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Base
        {
            get
            {
                return this.baseField;
            }
            set
            {
                this.baseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Subunit
        {
            get
            {
                return this.subunitField;
            }
            set
            {
                this.subunitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ToDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Referance
        {
            get
            {
                return this.referanceField;
            }
            set
            {
                this.referanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Appointment
        {
            get
            {
                return this.appointmentField;
            }
            set
            {
                this.appointmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface Service1SoapChannel : ServiceReference2.Service1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<ServiceReference2.Service1Soap>, ServiceReference2.Service1Soap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), Service1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.memberBasicInfoNBF[]> getSpecificMemberBasicInfoAsync(string NIC)
        {
            return base.Channel.getSpecificMemberBasicInfoAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.ServiceRecordHRMS[]> getServiceRecordsAsync(string NIC)
        {
            return base.Channel.getServiceRecordsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.MedalAndDecorationHRMS[]> getMedalAndDecorationAsync(string NIC)
        {
            return base.Channel.getMedalAndDecorationAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.InsigniaHRMS[]> getInsigniaAsync(string NIC)
        {
            return base.Channel.getInsigniaAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.DependentBasicInfoHRMS[]> getDependentBasicInfoAsync(string NIC)
        {
            return base.Channel.getDependentBasicInfoAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.PetDetailsHRMS[]> getPetDetailsAsync(string NIC)
        {
            return base.Channel.getPetDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.SwimmingDetailsHRMS[]> getSwimmingDetailsAsync(string NIC)
        {
            return base.Channel.getSwimmingDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.WeaponDetailsHRMS[]> getWeaponDetailsAsync(string NIC)
        {
            return base.Channel.getWeaponDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.ALDetailsHRMS[]> getALDetailsAsync(string NIC)
        {
            return base.Channel.getALDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.OLDetailsHRMS[]> getOLDetailsAsync(string NIC)
        {
            return base.Channel.getOLDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.KitZiseHRMS[]> getKitZiseAsync(string NIC)
        {
            return base.Channel.getKitZiseAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.SportDetailsHRMS[]> getSportDetailsAsync(string NIC)
        {
            return base.Channel.getSportDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.NavalDetailsHRMS[]> getNavalDetailsAsync(string NIC)
        {
            return base.Channel.getNavalDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.GCBDetailsHRMS[]> getGCBDetailsAsync(string NIC)
        {
            return base.Channel.getGCBDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.SchoolDetailsHRMS[]> getSchoolDetailsAsync(string NIC)
        {
            return base.Channel.getSchoolDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.CourseDetailsHRMS[]> getCourseDetailsAsync(string NIC)
        {
            return base.Channel.getCourseDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.ExamDetailsHRMS[]> getExamDetailsAsync(string NIC)
        {
            return base.Channel.getExamDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.BirthDayMedicalDetailsHRMS[]> getBirthDayMedicalDetailsAsync(string NIC)
        {
            return base.Channel.getBirthDayMedicalDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.TatooDetailsHRMS[]> getTatooDetailsAsync(string NIC)
        {
            return base.Channel.getTatooDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.PunishmentDetailsHRMS[]> getPunishmentDetailsAsync(string NIC)
        {
            return base.Channel.getPunishmentDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.ArrestedSurrenderDetailsHRMS[]> getArrestedSurrenderDetailsAsync(string NIC)
        {
            return base.Channel.getArrestedSurrenderDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.ToursVisitsSeminar[]> getToursVisitsSeminarAsync(string NIC)
        {
            return base.Channel.getToursVisitsSeminarAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.SpecialQulificationDetailsHRMS[]> getSpecialQulificationDetailsAsync(string NIC)
        {
            return base.Channel.getSpecialQulificationDetailsAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.PromotionAdvancementHRMS[]> getPromotionAdvancementAsync(string NIC)
        {
            return base.Channel.getPromotionAdvancementAsync(NIC);
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.ColoursDetailsHRMS[]> getColoursDetailsAsync(string NIC)
        {
            return base.Channel.getColoursDetailsAsync(NIC);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.1.216:99/Service1.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://10.10.1.216:99/Service1.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Service1Soap,
            
            Service1Soap12,
        }
    }
}
